name: Main

on: [push, pull_request]

jobs:
  build:
    name: Test/Build/Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: project/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # # Test
      # - name: Run Tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      #     projectPath: project/

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          path: project/

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ${{ vars.BUILD_PATH }}

      # Deployment
      - name: Stash build result and reset local changes
        run: |
          echo "Applying initial configs"
          sudo chown -R $USER:$USER ${{ vars.BUILD_PATH }}
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          echo "Stash and reset"
          git add ${{ vars.BUILD_PATH }}/${{ vars.TARGET_PLATFORM }}
          git stash push ${{ vars.BUILD_PATH }}/${{ vars.TARGET_PLATFORM }}
          git stash list
          git reset --hard
          sudo git clean -d -x -f
    
      # Deployment
      - name: Cleaning gh-pages branch
        run: |
          echo "Switch to ${{ vars.DEPLOYMENT_BRANCH }}"
          git switch -f ${{ vars.DEPLOYMENT_BRANCH }}
          git reset --hard
          sudo git clean -d -x -f
          rm -r *
          git add *
          git commit -m "cleaning branch"
          git push
      - name: Applying stashed files to ${{ vars.DEPLOYMENT_BRANCH }}
        run: |
          echo "Applying stash"
          git stash apply stash@{0}
      - name: Copying files to root directory
        run: |
          cd ${{ vars.BUILD_PATH }}/${{ vars.TARGET_PLATFORM }}/${{ vars.TARGET_PLATFORM }}
          ls
          cp -r * ../../../
          cd ../../../
          rm -r ${{ vars.BUILD_PATH }}
          ls
          pwd
      - name: Pushing deployment to gh-pages branch
        run: |
          pwd
          git status
          git add *
          git commit -m "Deployment"
          git push
          git reset --hard
          sudo git clean -d -x -f